version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "5432:5432"  
    volumes:
      - pg_data:/var/lib/postgresql/data  

  analytics:
    build:
      context: .
      dockerfile: Dockerfile_python  
    volumes:
      - ./analytics:/app 
    depends_on:
      - db  
    command: ["python", "python_script.py"]  

volumes:
  pg_data:  

